// Generated by CoffeeScript 1.8.0
(function() {
  var Merge;

  Merge = (function() {
    function Merge(paper, branch_from, branch_to) {
      var path;
      this.paper = paper;
      this.branch_from = branch_from;
      this.branch_to = branch_to;
      if (this.branch_to.revision_start < this.branch_from.revision_start && this.branch_from.x > this.branch_to.x) {
        path = this.paper.path("M " + this.branch_to.x + " " + this.branch_to.revision_start + " V " + this.branch_to.revision_start + " C " + this.branch_to.x + " " + (this.branch_to.revision_start + 55) + " " + (this.branch_to.x + 50) + " " + (this.branch_to.revision_start + 45) + " " + (this.branch_to.x + 50) + " " + (this.branch_to.revision_start + 100));
      }
      if (this.branch_from.x < this.branch_to.x) {
        path = this.paper.path("M " + this.branch_from.x + " " + this.branch_from.revision_end + " V " + this.branch_from.start + " C " + this.branch_from.x + " " + (this.branch_from.revision_end - 55) + " " + this.branch_to.x + " " + (this.branch_from.revision_end - 50) + " " + this.branch_to.x + " " + (this.branch_from.revision_end - 100));
      }
      if (this.branch_to.revision_start > this.branch_from.revision_start && this.branch_from.x > this.branch_to.x) {
        path = this.paper.path("M " + this.branch_from.x + " " + this.branch_from.revision_end + " V " + this.branch_from.revision_end + " C " + this.branch_from.x + " " + (this.branch_from.revision_end - 55) + " " + this.branch_to.x + " " + (this.branch_from.revision_end - 50) + " " + this.branch_to.x + " " + (this.branch_from.revision_end - 100));
      }
      if (this.branch_to.revision_start < this.branch_from.revision_start && this.branch_to.x > this.branch_from.x) {
        path = this.paper.path("M " + this.branch_to.x + " " + this.branch_to.revision_start + " V " + this.branch_to.revision_start + " C " + this.branch_to.x + " " + (this.branch_to.revision_start + 55) + " " + this.branch_from.x + " " + (this.branch_to.revision_start + 50) + " " + this.branch_from.x + " " + (this.branch_to.revision_start + 100));
      }
      if (path !== void 0) {
        path.attr("stroke", this.color);
        path.attr("stroke-width", "3");
      }
    }

    return Merge;

  })();

  window.Merge = Merge;

}).call(this);
