// Generated by CoffeeScript 1.8.0
(function() {
  var CIRCLE_HOVER_RADIUS, CIRCLE_RADIUS, Revision, over,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CIRCLE_RADIUS = 5;

  CIRCLE_HOVER_RADIUS = 10;

  over = false;

  Revision = (function() {
    function Revision(branch, y_position, response) {
      var circle;
      this.branch = branch;
      this.y_position = y_position;
      this.response = response;
      this.getNode = __bind(this.getNode, this);
      circle = this.branch.paper.circle(this.branch.x, this.y_position, CIRCLE_RADIUS);
      circle.attr('fill', this.branch.color);
      circle.attr('stroke', this.branch.color);
      circle.mouseover(function() {
        return this.animate({
          r: CIRCLE_HOVER_RADIUS
        }, 100);
      });
      circle.mouseout(function() {
        return this.animate({
          r: CIRCLE_RADIUS
        }, 100);
      });
      this.circle = circle;
      this.register(this.response);
    }

    Revision.prototype.getNode = function() {
      return this.circle.node;
    };

    Revision.prototype.register = function(response) {
      var node, tip;
      tip = $("#tip");
      node = this.circle.node;
      return $(node).on('mouseenter', function() {
        tip.html(response.message);
        tip.fadeIn();
        return over = true;
      }).on('mouseleave', function() {
        tip.fadeOut(200);
        return over = false;
      });
    };

    return Revision;

  })();

  window.Revision = Revision;

}).call(this);
