// Generated by CoffeeScript 1.8.0
(function() {
  var get, over, owner, repo;

  window.App = Ember.Application.create();

  App.Commit = Ember.Object.extend();

  App.ListCommits = Ember.ArrayController.create({});

  owner = 'vinicarlos56';

  repo = 'html5-revision-graph';

  over = true;

  get = function(sha, master) {
    return $.getJSON("https://api.github.com/repos/" + owner + "/" + repo + "/git/commits/" + sha).then(function(response) {
      if (typeof master.getLastRevision() !== "undefined") {
        master.addRevision(new Revision(master, master.getLastRevision().y_position - 50, response));
      } else {
        master.addRevision(new Revision(master, 500, response));
      }
      if (typeof response.parents[0] !== "undefined") {
        return get(response.parents[0].sha, master);
      }
    });
  };

  $(document).ready(function() {
    var canvas_container, height, master, paper, x_master;
    canvas_container = document.getElementById('canvas_container');
    paper = new Raphael(canvas_container, 600, 500);
    x_master = 450;
    height = 500;
    master = new Branch(paper, 450, 0, 500, 'red');
    master.draw();
    get('717e721cf1b5255938e930af4872135601f8d841', master);
    return $(document).mousemove(function(e) {
      if (over) {
        return $('#tip').css("left", e.clientX + 20).css("top", e.clientY + 20);
      }
    });
  });

  return;

  jQuery(function() {
    var canvas_container, height, master, paper, rev, x_master;
    canvas_container = document.getElementById('canvas_container');
    paper = new Raphael(canvas_container, 600, 500);
    x_master = 450;
    height = 500;
    master = new Branch(paper, 450, 0, 500, 'red');
    master.draw();
    rev = new Revision(master, 450);
    master.addRevision(rev);
    console.log(master.getLastRevision());
  });

}).call(this);
